version: '3'
services:
  pubnow-backend:
    build: '.'
    # container_name: 'pubnow-backend'
    depends_on:
      - pubnow-db
    environment:
      - DB_URI=postgres://root:password@pubnow-db/db?charset=UTF8
    ports:
      - '7101:7101'
    volumes:
      - .:/opt/app

  pubnow-db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres:11
    ports:
      - 0.0.0.0:7200:5432
